services:
  - type: web
    name: cybix-cc-bot
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        value: "6524840104"
      - key: CHANNEL_ID
        value: "@cybixtech"
      - key: RENDER_EXTERNAL_URL
        sync: false
    autoDeploy: true