services:
  - type: web
    name: cybix-cc-gen
    env: node
    plan: free
    buildCommand: "yarn install"
    startCommand: "node index.js"
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true