services:
  - type: web
    name: cybix-cc-bot
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
    autoDeploy: true
    healthCheckPath: /
    repo: https://github.com/Ash-Lynx1/CYBIX-CC-GEN